; Supervisor configuration file for CrystalClearHouse
; Reference: http://supervisord.org/configuration.html

[unix_http_server]
file=/tmp/supervisor.sock   ; socket file path
chmod=0700                  ; socket file mode

[supervisord]
logfile=/tmp/supervisord.log ; main log file
logfile_maxbytes=50MB        ; max main logfile bytes
logfile_backups=10           ; number of logfile backups
loglevel=info                ; log level
pidfile=/tmp/supervisord.pid ; pidfile location
nodaemon=false               ; run in foreground
silent=false                 ; no logs to stdout
minfds=1024                  ; min. avail startup file descriptors
minprocs=200                 ; min. avail process descriptors

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock ; use unix:// URL for socket

[include]
files = programs/*.conf
